"""
Django settings for django_core project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import importlib
from pathlib import Path
from decouple import config

system_configs = importlib.import_module(f"enviroments.env_{config('ENVIROMENT', default='local')}")

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-pajk1seij+@o=)_zhsg$q$3n#w&%8qnp4t2vjpgnxw$kkalw%f'

DEBUG = system_configs.DEBUG

ALLOWED_HOSTS = system_configs.ALLOWED_HOSTS

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = system_configs.MIDDLEWARE

ROOT_URLCONF = 'django_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_core.wsgi.application'

DATABASES = system_configs.DATABASES

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = system_configs.CACHES

SESSION_CACHE_ALIAS = system_configs.SESSION_CACHE_ALIAS

LANGUAGE_CODE = system_configs.LANGUAGE_CODE

TIME_ZONE = system_configs.TIME_ZONE

USE_I18N = system_configs.USE_I18N

USE_TZ = system_configs.USE_TZ

STATIC_URL = system_configs.STATIC_URL

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
